### ISSUE TITLE
Is macOS 10.14 host required?

### ISSUE THREAD

**Issue by yeahdongcn** [bacongravy/macinbox#13]
I was trying to run macinbox in my macOS 10.13.6 host and an error occurred `- Error: host OS version (10.13.6) and installer OS version (10.14) do not match`. Then I comment out `check_macos_versions` and everything works fine. So why checking the version of host?

**Comment by bacongravy** [comment]
Hello, @yeahdongcn! Thanks for the report.

It has been my understanding that, at least in the past, the `installer` tool only worked when the host machine version matched the version of the OS in the package, due to the packages depending on specific features the tool. Apparently that is no longer the case!

I'll verify that I too can run `macinbox` on 10.3.6 pointing at a 10.14 installer, and then I'll update the `check_macos_versions` function to be less strict.

**Comment by yeahdongcn** [comment]
Sounds great, thanks.

**Comment by bacongravy** [comment]
Fixed with https://github.com/bacongravy/macinbox/commit/7c13c2a6979aac8dcaa1b758d7d2138380682ab6. Version mismatch between host and installer now results in a warning instead of an error.

**Comment by yeahdongcn** [comment]
Really appreciate your quick action!
