### ISSUE TITLE
Parallels sed error

### ISSUE THREAD

**Issue by qrevel** [bacongravy/macinbox#16]
When building a parallels box, I got the following error:

```sudo macinbox --box-format parallels
• Creating image from installer...
  + Checking macOS versions...
  + Creating and attaching wrapper disk image...
  + Creating and attaching a new blank disk image...
  + Installing macOS...
    - installer: 100% done
  + Installing the Parallels Tools...
sed: can't read s/PARALLELS_ADDITIONAL_ARGS/--share/: No such file or directory
    - Error: sed failed with non-zero exit code: 2

• Cleaning up...
```

```
sudo macinbox --version
macinbox 2.0.1
```

```
prlctl --version
prlctl version 14.0.1 (45154)
```

**Comment by bacongravy** [comment]
Thank you for the report, @qrevel!  That error message suggests to me that somehow, the GNU version of `sed` was run instead of the built-in BSD version; I suspect that it is because they handle the `-i` argument differently.

The code in `macinbox` currently just invokes `sed` and relies on the PATH environment variable to indicate the lookup order for which version to use. Perhaps you have your PATH set such that a different version of `sed` is being invoked?

I will try to fix this by changing `macinbox` to invoke the system-provided `/usr/bin/sed` explicitly. In the meantime, you can try to workaround this issue by making sure your PATH is set such that the system `sed` is the one that gets invoked when running `macinbox`.  Please let me know if that does in fact resolve the issue for you.

**Comment by qrevel** [comment]
Yes you are right, I'm running the GNU sed instead of the system one.

It's working when I'm bypassing the system one

**Comment by bacongravy** [comment]
I have address this issue with https://github.com/bacongravy/macinbox/commit/3e04c2ca6333572b5f47dc418af0e60db138e1b9. The change will be in the forthcoming 3.0.0 release.

**Comment by bacongravy** [comment]
v3.0.0 has been released.
