### ISSUE TITLE
Unexpected behavior when installer already in DMG

### ISSUE THREAD

**Issue by epackorigan** [bacongravy/macinbox#21]
If you use `https://github.com/munki/macadmin-scripts/blob/master/installinstallmacos.py` to build DMGs for the installer, and mount those as the source for macinbox as `/Volumes/Install macOS Mojave`, the one created by macinbox ends up as `/Volumes/Install macOS Mojave 1`, and the first is the one that ends up being unmounted at the end of the process, leaving the other around...

Can the following features be implemented:
* Check to see if the installer is already in a DMG, and skip creating a new DMG to store the installer.
* Check where the new installer is mounted, and unmount that one.

**Comment by bacongravy** [comment]
Hi, @epackorigan! Thanks for letting me know about this issue.

I am already working on some unrelated changes that will address your second request; the wrapper image for the installer will be correctly unmounted using its device node instead of its supposed mountpoint.

I do like your first request; it would be much more efficient if the script detected that the installer was already in a DMG, and skipped creating the wrapper. I'll use this issue to track adding that behavior.

**Comment by bacongravy** [comment]
With the changes in https://github.com/bacongravy/macinbox/commit/73aa46bcb319026f71ab2b8abd5649bcd15a37f7 the correct installer disk image should now be getting unmounted.

**Comment by bacongravy** [comment]
With the changes in https://github.com/bacongravy/macinbox/commit/9623626feb64d866c1b5a3478e26c8c28d521cf9, creation of the wrapper image is now skipped if the installer app is on a non-root volume.

**Comment by bacongravy** [comment]
With the changes in https://github.com/bacongravy/macinbox/commit/1c5115e6a3ac7716efc1a2f2942ac2f8b04943c4 I have implemented a `--installer-dmg` option which allows you to specify an unmounted installer disk image (e.g. one created by `installinstallmacos.py`). The `macinbox` script will automatically mount and unmount this disk image as needed.

**Comment by bacongravy** [comment]
v3.2.0 has been released to rubygems.org. Closing.
