### ISSUE TITLE
Whitelisting of Kext's

### ISSUE THREAD

**Issue by egandro** [bacongravy/macinbox#24]
Hello,

can we make a nice --whitelist-known-kext flag?

I'd like to whitelist all "wellknown" kext e.g. vbox, virtualbox, docker, ... by the way you use for vmware.

This will reduce the number of clicks we have to do in postsetup.

(I will create a patch request within a few days).

**Comment by bacongravy** [comment]
Sure, @egandro, I'd be happy to consider a PR that adds such a feature, thought it does does seem like it may contradict the `macinbox` design philosophy:

> [T]his tool is also intended to the do the least amount of configuration possible. Nothing is done that could instead be deferred to a provisioning step in a Vagrantfile or packer template.

I think I'm willing to make an exception here, since `macinbox` already knows how to update the kext whitelist, and there's a clear benefit to getting the kext whitelisted before the first boot.

On the other hand, I wonder if it would be better to make this mechanism more generic; basically, a way for the user to specify a custom script that is run after the macOS installer finishes, and is provided with the path to the newly-installed OS so that it can make any modifications it wants.

**Comment by bacongravy** [comment]
@egandro please take a look at the `--user-script` feature I added in PR #27 and let me know if that would address your request.

**Comment by egandro** [comment]
I think yes - if we provide some cool examples.

**Comment by bacongravy** [comment]
The user script you want would look something like:

```
#!/bin/bash

cat << EOF | /usr/bin/sqlite3 "${1}/private/var/db/SystemPolicyConfiguration/KextPolicy"

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO kext_policy VALUES('xxxxxxxxxx','com.xxx.yyy.zzz,1,'Example, Inc.',1);
COMMIT;

EOF
```

To determine what values you need to insert into the KextPolicy database, first install the kexts on a running system and permit them to be loaded, and then run this command:

```
echo ".dump kext_policy" | sqlite3 /private/var/db/SystemPolicyConfiguration/KextPolicy
```

**Comment by bacongravy** [comment]
I've merged the PR to master: https://github.com/bacongravy/macinbox/commit/bcc8f9fbbe6ab6cb478bf44905779d16db4e5859

**Comment by bacongravy** [comment]
Tagged and released: https://github.com/bacongravy/macinbox/tree/v3.3.0
